stages:
  - prepare
  - deploy

variables:
  TF_VERSION: "1.1.0"
  AWS_DEFAULT_REGION: "us-east-1"

before_script:
  - curl -L https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip > terraform.zip
  - unzip terraform.zip
  - mv terraform /usr/local/bin/
  - rm terraform.zip
  - terraform init

prepare_network:
  stage: prepare
  script:
    - bash ./scripts/prepare_network.sh
  only:
    - main

deploy_infrastructure:
  stage: deploy
  script:
    - terraform apply -auto-approve
  only:
    - main